---

- name: Managing users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.username | default(item.username) }}"
    password: "{{ item.password }}"
    shell: /usr/sbin/nologin
  with_items: "{{ vsftpd_users }}"

- name: Setup userlist
  copy:
    content: "{{ vsftpd_users | map( attribute='username' ) | join('\n') }}\n"
    dest: "{{ vsftpd_userlist_path }}"
    owner: root
    group: root
    mode: 0644
  when: vsftpd_userlist

